"""Special tokens and mappings for the ChemNova Local Tokenizer."""

from typing import Dict, List

# Core sequence special tokens
PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"
BOS_TOKEN = "<BOS>"
EOS_TOKEN = "<EOS>"
MASK_TOKEN = "<MASK>"

# Structured chemistry & reasoning markers (Step 4 Directive 4)
CHEM_TOKEN = "<CHEM>"
FORMULA_TOKEN = "<FORMULA>"
SMILES_TOKEN = "<SMILES>"
REACTION_TOKEN = "<REACTION>"
QUESTION_TOKEN = "<QUESTION>"
ANSWER_TOKEN = "<ANSWER>"
REASONING_TOKEN = "<REASONING>"
END_TOKEN = "<END>"

# Conversational role tokens (preserving backward compatibility)
USER_TOKEN = "<USER>"
ASSISTANT_TOKEN = "<ASSISTANT>"
CHEMISTRY_TOKEN = "<CHEMISTRY>"

SPECIAL_TOKENS: List[str] = [
    PAD_TOKEN,
    UNK_TOKEN,
    BOS_TOKEN,
    EOS_TOKEN,
    MASK_TOKEN,
    CHEM_TOKEN,
    FORMULA_TOKEN,
    SMILES_TOKEN,
    REACTION_TOKEN,
    QUESTION_TOKEN,
    ANSWER_TOKEN,
    REASONING_TOKEN,
    END_TOKEN,
    USER_TOKEN,
    ASSISTANT_TOKEN,
    CHEMISTRY_TOKEN,
]

# Standard Special Token IDs
PAD_ID = 0
UNK_ID = 1
BOS_ID = 2
EOS_ID = 3
MASK_ID = 4
CHEM_ID = 5
FORMULA_ID = 6
SMILES_ID = 7
REACTION_ID = 8
QUESTION_ID = 9
ANSWER_ID = 10
REASONING_ID = 11
END_ID = 12
USER_ID = 13
ASSISTANT_ID = 14
CHEMISTRY_ID = 15

SPECIAL_TOKEN_TO_ID: Dict[str, int] = {
    PAD_TOKEN: PAD_ID,
    UNK_TOKEN: UNK_ID,
    BOS_TOKEN: BOS_ID,
    EOS_TOKEN: EOS_ID,
    MASK_TOKEN: MASK_ID,
    CHEM_TOKEN: CHEM_ID,
    FORMULA_TOKEN: FORMULA_ID,
    SMILES_TOKEN: SMILES_ID,
    REACTION_TOKEN: REACTION_ID,
    QUESTION_TOKEN: QUESTION_ID,
    ANSWER_TOKEN: ANSWER_ID,
    REASONING_TOKEN: REASONING_ID,
    END_TOKEN: END_ID,
    USER_TOKEN: USER_ID,
    ASSISTANT_TOKEN: ASSISTANT_ID,
    CHEMISTRY_TOKEN: CHEMISTRY_ID,
}

ID_TO_SPECIAL_TOKEN: Dict[int, str] = {v: k for k, v in SPECIAL_TOKEN_TO_ID.items()}
SPECIAL_TOKEN_MAP = SPECIAL_TOKEN_TO_ID
