"""
ChemSpace Database Module
Production-ready MySQL Persistence with Strict User Data Isolation
"""

from .connection import get_db_connection, get_db_pool, get_database_status
from .migrations import run_migrations
from .repository import (
    get_or_create_user,
    get_user_by_firebase_uid,
    update_user_profile,
    get_user_profile,
    get_user_preferences,
    update_user_preferences,
    list_user_files,
    create_user_file,
    get_user_file,
    delete_user_file,
    list_user_downloads,
    record_user_download,
    delete_user_download,
    list_user_recent_items,
    save_user_recent_item,
    delete_user_recent_item,
    list_user_projects,
    save_user_project,
    get_user_project,
    delete_user_project,
    list_user_molecules,
    save_user_molecule,
    get_user_molecule,
    delete_user_molecule,
    list_user_conversations,
    create_user_conversation,
    get_conversation_messages,
    add_conversation_message,
    log_user_activity,
    get_user_audit_logs,
)

__all__ = [
    "get_db_connection",
    "get_db_pool",
    "get_database_status",
    "run_migrations",
    "get_or_create_user",
    "get_user_by_firebase_uid",
    "update_user_profile",
    "get_user_profile",
    "get_user_preferences",
    "update_user_preferences",
    "list_user_files",
    "create_user_file",
    "get_user_file",
    "delete_user_file",
    "list_user_downloads",
    "record_user_download",
    "delete_user_download",
    "list_user_recent_items",
    "save_user_recent_item",
    "delete_user_recent_item",
    "list_user_projects",
    "save_user_project",
    "get_user_project",
    "delete_user_project",
    "list_user_molecules",
    "save_user_molecule",
    "get_user_molecule",
    "delete_user_molecule",
    "list_user_conversations",
    "create_user_conversation",
    "get_conversation_messages",
    "add_conversation_message",
    "log_user_activity",
    "get_user_audit_logs",
]
